// @generated by proof/Codegen.lean; DO NOT EDIT.
use crate::{EdgeContext, OracleCase};

#[rustfmt::skip]
pub static CASES: &[OracleCase] = &[
    OracleCase {
        name: "empty",
        offsets: &[0u32],
        destinations: &[],
        frontier: &[],
        expected_edges: &[],
        expected_source_counts: &[],
        expected_destination_counts: &[],
    },
    OracleCase {
        name: "ordered_rows",
        offsets: &[0u32, 2u32, 3u32, 5u32],
        destinations: &[1u32, 2u32, 2u32, 0u32, 1u32],
        frontier: &[2u32, 0u32],
        expected_edges: &[EdgeContext { source: 2u32, destination: 0u32, edge: 3u32 }, EdgeContext { source: 2u32, destination: 1u32, edge: 4u32 }, EdgeContext { source: 0u32, destination: 1u32, edge: 0u32 }, EdgeContext { source: 0u32, destination: 2u32, edge: 1u32 }],
        expected_source_counts: &[2u32, 2u32],
        expected_destination_counts: &[1u32, 2u32, 1u32],
    },
    OracleCase {
        name: "isolated_and_parallel_self_loops",
        offsets: &[0u32, 2u32, 2u32, 3u32],
        destinations: &[0u32, 0u32, 1u32],
        frontier: &[1u32, 0u32, 1u32],
        expected_edges: &[EdgeContext { source: 0u32, destination: 0u32, edge: 0u32 }, EdgeContext { source: 0u32, destination: 0u32, edge: 1u32 }],
        expected_source_counts: &[0u32, 2u32, 0u32],
        expected_destination_counts: &[2u32, 0u32, 0u32],
    },
    OracleCase {
        name: "duplicate_frontier",
        offsets: &[0u32, 1u32, 2u32],
        destinations: &[1u32, 0u32],
        frontier: &[0u32, 0u32, 1u32],
        expected_edges: &[EdgeContext { source: 0u32, destination: 1u32, edge: 0u32 }, EdgeContext { source: 0u32, destination: 1u32, edge: 0u32 }, EdgeContext { source: 1u32, destination: 0u32, edge: 1u32 }],
        expected_source_counts: &[1u32, 1u32, 1u32],
        expected_destination_counts: &[1u32, 2u32],
    },
    OracleCase {
        name: "parallel_edges_and_self_loop",
        offsets: &[0u32, 3u32, 4u32],
        destinations: &[1u32, 1u32, 0u32, 0u32],
        frontier: &[0u32],
        expected_edges: &[EdgeContext { source: 0u32, destination: 1u32, edge: 0u32 }, EdgeContext { source: 0u32, destination: 1u32, edge: 1u32 }, EdgeContext { source: 0u32, destination: 0u32, edge: 2u32 }],
        expected_source_counts: &[3u32],
        expected_destination_counts: &[1u32, 2u32],
    }
];
