import TraversalAlgebra

open TraversalAlgebra

namespace TraversalAlgebra.Codegen

def join (separator : String) : List String → String
  | [] => ""
  | first :: rest => rest.foldl (fun output item => output ++ separator ++ item) first

def renderU32 (value : Nat) : String :=
  toString value ++ "u32"

def renderSlice (render : α → String) (values : List α) : String :=
  "&[" ++ join ", " (values.map render) ++ "]"

def renderEdge (edge : EdgeContext) : String :=
  "EdgeContext { source: " ++ renderU32 edge.source ++
    ", destination: " ++ renderU32 edge.destination ++
    ", edge: " ++ renderU32 edge.edge ++ " }"

def renderCase (case : Oracle.Case) : String :=
  "    OracleCase {\n" ++
  "        name: \"" ++ case.name ++ "\",\n" ++
  "        offsets: " ++ renderSlice renderU32 case.graph.csrOffsets ++ ",\n" ++
  "        destinations: " ++ renderSlice renderU32 case.graph.csrDestinations ++ ",\n" ++
  "        frontier: " ++ renderSlice renderU32 case.frontier ++ ",\n" ++
  "        expected_edges: " ++ renderSlice renderEdge (Oracle.expectedEdges case) ++ ",\n" ++
  "        expected_source_counts: " ++
    renderSlice renderU32 (Oracle.expectedSourceCounts case) ++ ",\n" ++
  "        expected_destination_counts: " ++
    renderSlice renderU32 (Oracle.expectedDestinationCounts case) ++ ",\n" ++
  "    }"

def render : Except String String := do
  if let some invalid := Oracle.cases.find? (fun case => !Oracle.isValid case) then
    throw ("refusing to generate invalid oracle case: " ++ invalid.name)
  let rendered := join ",\n" (Oracle.cases.map renderCase)
  pure <|
    "// @generated by proof/Codegen.lean; DO NOT EDIT.\n" ++
    "use crate::{EdgeContext, OracleCase};\n\n" ++
    "#[rustfmt::skip]\n" ++
    "pub static CASES: &[OracleCase] = &[\n" ++ rendered ++ "\n];\n"

end TraversalAlgebra.Codegen

def main (arguments : List String) : IO UInt32 := do
  match arguments with
  | [output] =>
      match TraversalAlgebra.Codegen.render with
      | .ok source =>
          IO.FS.writeFile output source
          IO.println ("generated " ++ output)
          return 0
      | .error message =>
          IO.eprintln message
          return 1
  | _ =>
      IO.eprintln "usage: codegen OUTPUT.rs"
      return 2
