use std::marker::PhantomData;

use cubecl::prelude::*;

use crate::detail::device::{
    DeviceVec, KernelColumn, KernelColumnAt, KernelColumnBindings, S0, S1, S2, S3,
};
use crate::expr::{DeviceGpuExpr, GpuExpr};
use crate::iter::MIter;
use crate::op;
use crate::runtime::{Executor, Scalar};
use crate::{Error, MItem};

/// Lazy slice that returns the same value for every logical index.
#[derive(Clone, Copy, Debug)]
pub struct ConstantSlice<T> {
    len: usize,
    value: T,
}

/// Lazy slice that returns the logical index as `u32`.
#[derive(Clone, Copy, Debug)]
pub struct TabulateSlice {
    len: usize,
}

/// Lazy slice generated by transforming one logical item from an `MIter`.
#[derive(Debug)]
pub struct TransformSlice<R, Input, Op, Output>
where
    R: Runtime,
    Input: MIter<R>,
{
    len: usize,
    input: Input,
    _marker: PhantomData<fn() -> (R, Op, Output)>,
}

impl<R, Input, Op, Output> Clone for TransformSlice<R, Input, Op, Output>
where
    R: Runtime,
    Input: MIter<R> + Clone,
{
    fn clone(&self) -> Self {
        Self {
            len: self.len,
            input: self.input.clone(),
            _marker: PhantomData,
        }
    }
}

impl<R, Input, Op, Output> Copy for TransformSlice<R, Input, Op, Output>
where
    R: Runtime,
    Input: MIter<R> + Copy,
{
}

#[doc(hidden)]
#[derive(Clone)]
pub struct ConstantRead<R: Runtime, T> {
    len: usize,
    value: DeviceVec<R, T>,
}

#[doc(hidden)]
#[derive(Clone, Copy, Debug)]
pub struct TabulateRead<R: Runtime> {
    len: usize,
    _marker: PhantomData<fn() -> R>,
}

#[doc(hidden)]
#[derive(Clone, Copy, Debug)]
pub struct TransformRead<R, Source, Op, Output> {
    pub(crate) len: usize,
    pub(crate) source: Source,
    _marker: PhantomData<fn() -> (R, Op, Output)>,
}

#[doc(hidden)]
pub struct ConstantExpr<T>(PhantomData<fn() -> T>);

#[doc(hidden)]
pub struct TabulateExpr;

#[doc(hidden)]
pub struct TransformExpr<R, InputExpr, Op, Output>(PhantomData<fn() -> (R, InputExpr, Op, Output)>);

#[doc(hidden)]
pub struct TransformExpr2<R, LeftExpr, RightExpr, Op, Output>(
    PhantomData<fn() -> (R, LeftExpr, RightExpr, Op, Output)>,
);

#[doc(hidden)]
pub struct TransformExpr3<R, FirstExpr, SecondExpr, ThirdExpr, Op, Output>(
    PhantomData<fn() -> (R, FirstExpr, SecondExpr, ThirdExpr, Op, Output)>,
);

/// Creates a lazy slice that returns `value` for every index.
pub fn constant_slice<T>(len: usize, value: T) -> ConstantSlice<T>
where
    T: Scalar,
{
    ConstantSlice { len, value }
}

/// Creates a lazy `u32` slice whose value is its logical index.
pub fn tabulate_slice(len: usize) -> TabulateSlice {
    TabulateSlice { len }
}

/// Creates a lazy slice by applying `Op` to each logical item of `input`.
pub fn transform_slice<R, Input, Op, Output>(
    input: Input,
    _op: Op,
) -> TransformSlice<R, Input, Op, Output>
where
    R: Runtime,
    Input: MIter<R>,
    Output: Scalar,
    Op: op::UnaryOp<R, Input::Item, Output = (Output,)>,
{
    let len = input.len();
    TransformSlice {
        len,
        input,
        _marker: PhantomData,
    }
}

impl<R, T> crate::slice::MSlice<R> for ConstantSlice<T>
where
    R: Runtime,
    T: Scalar + 'static,
{
    type Item = T;
    type Read = ConstantRead<R, T>;

    fn len(&self) -> usize {
        self.len
    }

    fn validate_executor(&self, _exec: &Executor<R>) -> Result<(), Error> {
        Ok(())
    }

    fn into_read(self, policy: &crate::detail::CubePolicy<R>) -> Result<Self::Read, Error> {
        Ok(ConstantRead {
            len: self.len,
            value: policy.to_device(&[self.value])?,
        })
    }
}

impl<R> crate::slice::MSlice<R> for TabulateSlice
where
    R: Runtime,
{
    type Item = u32;
    type Read = TabulateRead<R>;

    fn len(&self) -> usize {
        self.len
    }

    fn validate_executor(&self, _exec: &Executor<R>) -> Result<(), Error> {
        Ok(())
    }

    fn into_read(self, _policy: &crate::detail::CubePolicy<R>) -> Result<Self::Read, Error> {
        Ok(TabulateRead {
            len: self.len,
            _marker: PhantomData,
        })
    }
}

impl<R, Input, Op, Output> crate::slice::MSlice<R> for TransformSlice<R, Input, Op, Output>
where
    R: Runtime,
    Input: MIter<R>,
    Input::Item: MItem<R>,
    Output: Scalar + 'static,
    Op: op::UnaryOp<R, Input::Item, Output = (Output,)>,
    TransformRead<R, Input::Inner, Op, Output>:
        crate::detail::impls::IntoMaterializedColumn<R, Output>,
{
    type Item = Output;
    type Read = TransformRead<R, Input::Inner, Op, Output>;

    fn len(&self) -> usize {
        self.len
    }

    fn validate_executor(&self, _exec: &Executor<R>) -> Result<(), Error> {
        Ok(())
    }

    fn into_read(self, policy: &crate::detail::CubePolicy<R>) -> Result<Self::Read, Error> {
        Ok(TransformRead {
            len: self.len,
            source: self.input.into_inner_with_policy(policy)?,
            _marker: PhantomData,
        })
    }
}

impl<R, T> KernelColumn for ConstantRead<R, T>
where
    R: Runtime,
    T: Scalar + 'static,
{
    type Runtime = R;
    type Item = T;
    type Expr = ConstantExpr<T>;

    fn len(&self) -> usize {
        self.len
    }

    fn validate(&self) -> Result<(), Error> {
        Ok(())
    }
}

impl<R, T> KernelColumnAt<S0> for ConstantRead<R, T>
where
    R: Runtime,
    T: Scalar + 'static,
{
    type ExprAt = ConstantExpr<T>;
    type Next = S1;

    fn stage_at(&self, bindings: &mut KernelColumnBindings) -> Result<(), Error> {
        bindings.push(self.value.handle.clone(), self.value.len);
        Ok(())
    }
}

impl<R> KernelColumn for TabulateRead<R>
where
    R: Runtime,
{
    type Runtime = R;
    type Item = u32;
    type Expr = TabulateExpr;

    fn len(&self) -> usize {
        self.len
    }

    fn validate(&self) -> Result<(), Error> {
        Ok(())
    }
}

macro_rules! impl_tabulate_read_at {
    ($state:ty => $next:ty) => {
        impl<R> KernelColumnAt<$state> for TabulateRead<R>
        where
            R: Runtime,
        {
            type ExprAt = TabulateExpr;
            type Next = $state;

            fn stage_at(&self, _bindings: &mut KernelColumnBindings) -> Result<(), Error> {
                Ok(())
            }
        }
    };
}

impl_tabulate_read_at!(S0 => S0);
impl_tabulate_read_at!(S1 => S1);
impl_tabulate_read_at!(S2 => S2);
impl_tabulate_read_at!(S3 => S3);

impl<R, Source, Op, Output> KernelColumn for TransformRead<R, Source, Op, Output>
where
    R: Runtime,
    Source: KernelColumn<Runtime = R, Item = Output> + KernelColumnAt<S0>,
    (Output,): MItem<R>,
    Output: Scalar + 'static,
    Op: op::UnaryOp<R, (Output,), Output = (Output,)>,
{
    type Runtime = R;
    type Item = Output;
    type Expr = TransformExpr<R, Source::Expr, Op, Output>;

    fn len(&self) -> usize {
        self.len
    }

    fn validate(&self) -> Result<(), Error> {
        self.source.validate()
    }
}

impl<R, Source, Op, Output> KernelColumnAt<S0> for TransformRead<R, Source, Op, Output>
where
    R: Runtime,
    Source: KernelColumn<Runtime = R, Item = Output> + KernelColumnAt<S0>,
    (Output,): MItem<R>,
    Output: Scalar + 'static,
    Op: op::UnaryOp<R, (Output,), Output = (Output,)>,
{
    type ExprAt = TransformExpr<R, Source::Expr, Op, Output>;
    type Next = <Source as KernelColumnAt<S0>>::Next;

    fn stage_at(&self, bindings: &mut KernelColumnBindings) -> Result<(), Error> {
        self.source.stage_at(bindings)
    }
}

impl<R, Source, Op, Output> KernelColumn for TransformRead<R, (Source,), Op, Output>
where
    R: Runtime,
    Source: KernelColumn<Runtime = R, Item = Output> + KernelColumnAt<S0>,
    (Output,): MItem<R>,
    Output: Scalar + 'static,
    Op: op::UnaryOp<R, (Output,), Output = (Output,)>,
{
    type Runtime = R;
    type Item = Output;
    type Expr = TransformExpr<R, Source::Expr, Op, Output>;

    fn len(&self) -> usize {
        self.len
    }

    fn validate(&self) -> Result<(), Error> {
        self.source.0.validate()
    }
}

impl<R, Source, Op, Output> KernelColumnAt<S0> for TransformRead<R, (Source,), Op, Output>
where
    R: Runtime,
    Source: KernelColumn<Runtime = R, Item = Output> + KernelColumnAt<S0>,
    (Output,): MItem<R>,
    Output: Scalar + 'static,
    Op: op::UnaryOp<R, (Output,), Output = (Output,)>,
{
    type ExprAt = TransformExpr<R, Source::Expr, Op, Output>;
    type Next = <Source as KernelColumnAt<S0>>::Next;

    fn stage_at(&self, bindings: &mut KernelColumnBindings) -> Result<(), Error> {
        self.source.0.stage_at(bindings)
    }
}

impl<R, Left, Right, Op, Output> KernelColumn for TransformRead<R, (Left, Right), Op, Output>
where
    R: Runtime,
    Left: KernelColumn<Runtime = R, Item = Output> + KernelColumnAt<S0>,
    Right: KernelColumn<Runtime = R, Item = Output> + KernelColumnAt<S1>,
    Output: Scalar + 'static,
    Op: op::UnaryOp<R, (Output, Output), Output = (Output,)>,
    <Left as KernelColumnAt<S0>>::ExprAt: GpuExpr<Output> + DeviceGpuExpr<Output>,
    <Right as KernelColumnAt<S1>>::ExprAt: GpuExpr<Output> + DeviceGpuExpr<Output>,
{
    type Runtime = R;
    type Item = Output;
    type Expr = TransformExpr2<
        R,
        <Left as KernelColumnAt<S0>>::ExprAt,
        <Right as KernelColumnAt<S1>>::ExprAt,
        Op,
        Output,
    >;

    fn len(&self) -> usize {
        self.len
    }

    fn validate(&self) -> Result<(), Error> {
        self.source.0.validate()?;
        self.source.1.validate()?;
        crate::error::ensure_same_len(self.source.0.len(), self.source.1.len())
    }
}

impl<R, Left, Right, Op, Output> KernelColumnAt<S0> for TransformRead<R, (Left, Right), Op, Output>
where
    R: Runtime,
    Left: KernelColumn<Runtime = R, Item = Output> + KernelColumnAt<S0>,
    Right: KernelColumn<Runtime = R, Item = Output> + KernelColumnAt<S1>,
    Output: Scalar + 'static,
    Op: op::UnaryOp<R, (Output, Output), Output = (Output,)>,
    <Left as KernelColumnAt<S0>>::ExprAt: GpuExpr<Output> + DeviceGpuExpr<Output>,
    <Right as KernelColumnAt<S1>>::ExprAt: GpuExpr<Output> + DeviceGpuExpr<Output>,
{
    type ExprAt = TransformExpr2<
        R,
        <Left as KernelColumnAt<S0>>::ExprAt,
        <Right as KernelColumnAt<S1>>::ExprAt,
        Op,
        Output,
    >;
    type Next = S2;

    fn stage_at(&self, bindings: &mut KernelColumnBindings) -> Result<(), Error> {
        self.source.0.stage_at(bindings)?;
        self.source.1.stage_at(bindings)
    }
}

impl<R, First, Second, Third, Op, Output> KernelColumn
    for TransformRead<R, (First, Second, Third), Op, Output>
where
    R: Runtime,
    First: KernelColumn<Runtime = R, Item = Output> + KernelColumnAt<S0>,
    Second: KernelColumn<Runtime = R, Item = Output> + KernelColumnAt<S1>,
    Third: KernelColumn<Runtime = R, Item = Output> + KernelColumnAt<S2>,
    Output: Scalar + 'static,
    Op: op::UnaryOp<R, (Output, Output, Output), Output = (Output,)>,
    <First as KernelColumnAt<S0>>::ExprAt: GpuExpr<Output> + DeviceGpuExpr<Output>,
    <Second as KernelColumnAt<S1>>::ExprAt: GpuExpr<Output> + DeviceGpuExpr<Output>,
    <Third as KernelColumnAt<S2>>::ExprAt: GpuExpr<Output> + DeviceGpuExpr<Output>,
{
    type Runtime = R;
    type Item = Output;
    type Expr = TransformExpr3<
        R,
        <First as KernelColumnAt<S0>>::ExprAt,
        <Second as KernelColumnAt<S1>>::ExprAt,
        <Third as KernelColumnAt<S2>>::ExprAt,
        Op,
        Output,
    >;

    fn len(&self) -> usize {
        self.len
    }

    fn validate(&self) -> Result<(), Error> {
        self.source.0.validate()?;
        self.source.1.validate()?;
        self.source.2.validate()?;
        crate::error::ensure_same_len(self.source.0.len(), self.source.1.len())?;
        crate::error::ensure_same_len(self.source.0.len(), self.source.2.len())
    }
}

impl<R, First, Second, Third, Op, Output> KernelColumnAt<S0>
    for TransformRead<R, (First, Second, Third), Op, Output>
where
    R: Runtime,
    First: KernelColumn<Runtime = R, Item = Output> + KernelColumnAt<S0>,
    Second: KernelColumn<Runtime = R, Item = Output> + KernelColumnAt<S1>,
    Third: KernelColumn<Runtime = R, Item = Output> + KernelColumnAt<S2>,
    Output: Scalar + 'static,
    Op: op::UnaryOp<R, (Output, Output, Output), Output = (Output,)>,
    <First as KernelColumnAt<S0>>::ExprAt: GpuExpr<Output> + DeviceGpuExpr<Output>,
    <Second as KernelColumnAt<S1>>::ExprAt: GpuExpr<Output> + DeviceGpuExpr<Output>,
    <Third as KernelColumnAt<S2>>::ExprAt: GpuExpr<Output> + DeviceGpuExpr<Output>,
{
    type ExprAt = TransformExpr3<
        R,
        <First as KernelColumnAt<S0>>::ExprAt,
        <Second as KernelColumnAt<S1>>::ExprAt,
        <Third as KernelColumnAt<S2>>::ExprAt,
        Op,
        Output,
    >;
    type Next = S3;

    fn stage_at(&self, bindings: &mut KernelColumnBindings) -> Result<(), Error> {
        self.source.0.stage_at(bindings)?;
        self.source.1.stage_at(bindings)?;
        self.source.2.stage_at(bindings)
    }
}

#[cube]
impl<T> GpuExpr<T> for ConstantExpr<T>
where
    T: CubePrimitive,
{
    fn eval(input: &[T], _indices: &[u32], _rhs: &[T], _rhs_indices: &[u32], _index: usize) -> T {
        input[0]
    }
}

#[cube]
impl<T> DeviceGpuExpr<T> for ConstantExpr<T>
where
    T: CubePrimitive,
{
    fn eval(
        slot0: &[T],
        _slot1: &[T],
        _slot2: &[T],
        _slot3: &[T],
        _slot_offsets: &[u32],
        _index: usize,
    ) -> T {
        slot0[0]
    }
}

#[cube]
impl GpuExpr<u32> for TabulateExpr {
    fn eval(
        _input: &[u32],
        _indices: &[u32],
        _rhs: &[u32],
        _rhs_indices: &[u32],
        index: usize,
    ) -> u32 {
        index as u32
    }
}

#[cube]
impl DeviceGpuExpr<u32> for TabulateExpr {
    fn eval(
        _slot0: &[u32],
        _slot1: &[u32],
        _slot2: &[u32],
        _slot3: &[u32],
        _slot_offsets: &[u32],
        index: usize,
    ) -> u32 {
        index as u32
    }
}

#[cube]
impl<R, InputExpr, Op, Output> GpuExpr<Output> for TransformExpr<R, InputExpr, Op, Output>
where
    R: Runtime,
    InputExpr: GpuExpr<Output>,
    Output: Scalar,
    Op: op::UnaryOp<R, (Output,), Output = (Output,)>,
{
    fn eval(
        input: &[Output],
        indices: &[u32],
        rhs: &[Output],
        rhs_indices: &[u32],
        index: usize,
    ) -> Output {
        let value = InputExpr::eval(input, indices, rhs, rhs_indices, index);
        Op::apply((value,)).0
    }
}

#[cube]
impl<R, InputExpr, Op, Output> DeviceGpuExpr<Output> for TransformExpr<R, InputExpr, Op, Output>
where
    R: Runtime,
    InputExpr: DeviceGpuExpr<Output>,
    Output: Scalar,
    Op: op::UnaryOp<R, (Output,), Output = (Output,)>,
{
    fn eval(
        slot0: &[Output],
        slot1: &[Output],
        slot2: &[Output],
        slot3: &[Output],
        slot_offsets: &[u32],
        index: usize,
    ) -> Output {
        let value = InputExpr::eval(slot0, slot1, slot2, slot3, slot_offsets, index);
        Op::apply((value,)).0
    }
}

#[cube]
impl<R, LeftExpr, RightExpr, Op, Output> GpuExpr<Output>
    for TransformExpr2<R, LeftExpr, RightExpr, Op, Output>
where
    R: Runtime,
    LeftExpr: GpuExpr<Output>,
    RightExpr: GpuExpr<Output>,
    Output: Scalar,
    Op: op::UnaryOp<R, (Output, Output), Output = (Output,)>,
{
    fn eval(
        input: &[Output],
        indices: &[u32],
        rhs: &[Output],
        rhs_indices: &[u32],
        index: usize,
    ) -> Output {
        let left = LeftExpr::eval(input, indices, rhs, rhs_indices, index);
        let right = RightExpr::eval(input, indices, rhs, rhs_indices, index);
        Op::apply((left, right)).0
    }
}

#[cube]
impl<R, LeftExpr, RightExpr, Op, Output> DeviceGpuExpr<Output>
    for TransformExpr2<R, LeftExpr, RightExpr, Op, Output>
where
    R: Runtime,
    LeftExpr: DeviceGpuExpr<Output>,
    RightExpr: DeviceGpuExpr<Output>,
    Output: Scalar,
    Op: op::UnaryOp<R, (Output, Output), Output = (Output,)>,
{
    fn eval(
        slot0: &[Output],
        slot1: &[Output],
        slot2: &[Output],
        slot3: &[Output],
        slot_offsets: &[u32],
        index: usize,
    ) -> Output {
        let left = LeftExpr::eval(slot0, slot1, slot2, slot3, slot_offsets, index);
        let right = RightExpr::eval(slot0, slot1, slot2, slot3, slot_offsets, index);
        Op::apply((left, right)).0
    }
}

#[cube]
impl<R, FirstExpr, SecondExpr, ThirdExpr, Op, Output> GpuExpr<Output>
    for TransformExpr3<R, FirstExpr, SecondExpr, ThirdExpr, Op, Output>
where
    R: Runtime,
    FirstExpr: GpuExpr<Output>,
    SecondExpr: GpuExpr<Output>,
    ThirdExpr: GpuExpr<Output>,
    Output: Scalar,
    Op: op::UnaryOp<R, (Output, Output, Output), Output = (Output,)>,
{
    fn eval(
        input: &[Output],
        indices: &[u32],
        rhs: &[Output],
        rhs_indices: &[u32],
        index: usize,
    ) -> Output {
        let first = FirstExpr::eval(input, indices, rhs, rhs_indices, index);
        let second = SecondExpr::eval(input, indices, rhs, rhs_indices, index);
        let third = ThirdExpr::eval(input, indices, rhs, rhs_indices, index);
        Op::apply((first, second, third)).0
    }
}

#[cube]
impl<R, FirstExpr, SecondExpr, ThirdExpr, Op, Output> DeviceGpuExpr<Output>
    for TransformExpr3<R, FirstExpr, SecondExpr, ThirdExpr, Op, Output>
where
    R: Runtime,
    FirstExpr: DeviceGpuExpr<Output>,
    SecondExpr: DeviceGpuExpr<Output>,
    ThirdExpr: DeviceGpuExpr<Output>,
    Output: Scalar,
    Op: op::UnaryOp<R, (Output, Output, Output), Output = (Output,)>,
{
    fn eval(
        slot0: &[Output],
        slot1: &[Output],
        slot2: &[Output],
        slot3: &[Output],
        slot_offsets: &[u32],
        index: usize,
    ) -> Output {
        let first = FirstExpr::eval(slot0, slot1, slot2, slot3, slot_offsets, index);
        let second = SecondExpr::eval(slot0, slot1, slot2, slot3, slot_offsets, index);
        let third = ThirdExpr::eval(slot0, slot1, slot2, slot3, slot_offsets, index);
        Op::apply((first, second, third)).0
    }
}
